### ISSUE TITLE
Ask for usage help

### ISSUE THREAD

**Issue by brant-ruan** [Netflix/stethoscope#36]
Hello!
First thanks for your excellent software.
I have installed the front-end and back-end on my Ubuntu, but how can I use it?
I'm sorry, but I have read `README.md` and your https://stethoscope.readthedocs.io/en/latest/ for installation and running the front-end and back-end.
When I have the front-end and back-end up, what is the next step(how to use it)?
Exactly, how can I add new device to be monitored?
I am a newbie, and can you give me some help or leave helpful URL(s)?
Anyway, thanks a lot.

**Comment by andrewmwhite** [comment]
Stethoscope is designed to be used in a corporate or group environment that already has a systems management/information tool like LANDESK or JAMF deployed on each device. Since Stethoscope doesn't have it's own agent to collect information, it doesn't know anything about your devices except what it can gather from external data sources like those. 

Hopefully that answers your question, though unfortunately it sounds like Stethoscope may not be the right solution for you (unless I'm misunderstanding what you're asking).
