### ISSUE TITLE
Is it a plan to move the database to use docker as well? 

### ISSUE THREAD

**Issue by wubenhe** [Netflix/stethoscope#4]
I am a linux user, the doc is easy to follow until I saw the database installing is not using the docker. Is it any plan to move them into docker all together? If not then what is the reason of it?

**Comment by Winterspite** [comment]
Generally there's [some good reasons](https://myopsblog.wordpress.com/2017/02/06/why-databases-is-not-for-containers/) for not putting the database into a docker container as well when you're looking at persistent data storage. Not sure if that's why Netflix made the decision or not, but just more food for thought.

**Comment by jkriss** [comment]
@wubenhe: There's no database for the core Stethoscope backend. In our case, the datastores we use (e.g. SQL for LANDESK, elasticsearch for notifications) are maintained outside of our Stethoscope deployment. For local development and testing, we still use the production data sources, since they are read-only.
